#!/bin/bash
# One-time setup for a STABLE Cloudflare named tunnel.
#
# Usage:
#   ./bridge/setup-tunnel.sh <tunnel-name> <hostname>
#
# Example:
#   ./bridge/setup-tunnel.sh phantom-bridge bridge.example.com
#
# Prereqs (all free):
#   1. `brew install cloudflared`
#   2. A domain registered AND using Cloudflare DNS (move nameservers if
#      needed via the CF dashboard — it's free and takes <10 min).
#
# What it does:
#   1. `cloudflared login` if not already authorized (opens a browser).
#   2. Creates a named tunnel (skipped if one with that name already exists).
#   3. Creates a CNAME on your CF DNS so <hostname> → tunnel.
#   4. Writes bridge/cloudflared.yml so run-bridge.sh picks up named-mode.
#
# After this, every `./run-bridge.sh` produces the SAME public URL.

set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "usage: $0 <tunnel-name> <hostname>" >&2
    echo "example: $0 phantom-bridge bridge.example.com" >&2
    exit 2
fi

NAME="$1"
HOSTNAME="$2"

cd "$(dirname "$0")/.."
BRIDGE_DIR="$(pwd)/bridge"
CFG="$BRIDGE_DIR/cloudflared.yml"

if ! command -v cloudflared > /dev/null; then
    echo "error: cloudflared not installed. run: brew install cloudflared" >&2
    exit 1
fi

# 1. Login (browser flow). Cert lands at ~/.cloudflared/cert.pem.
if [[ ! -f "$HOME/.cloudflared/cert.pem" ]]; then
    echo "→ no cloudflared cert yet. running 'cloudflared login' …"
    echo "  a browser window will open — pick the zone for $HOSTNAME"
    cloudflared login
fi

# 2. Create the tunnel if it doesn't exist already.
EXISTING_UUID=$(cloudflared tunnel list --output json 2>/dev/null \
    | python3 -c "import json,sys
data = json.load(sys.stdin) if sys.stdin.isatty() == False else []
for t in data:
    if t.get('name') == '$NAME':
        print(t.get('id')); break
" 2>/dev/null || true)

if [[ -z "$EXISTING_UUID" ]]; then
    echo "→ creating tunnel '$NAME' …"
    cloudflared tunnel create "$NAME"
    EXISTING_UUID=$(cloudflared tunnel list --output json | python3 -c "
import json,sys
for t in json.load(sys.stdin):
    if t.get('name') == '$NAME':
        print(t.get('id')); break
")
else
    echo "→ tunnel '$NAME' already exists (uuid $EXISTING_UUID), reusing."
fi

CREDS="$HOME/.cloudflared/$EXISTING_UUID.json"
if [[ ! -f "$CREDS" ]]; then
    echo "error: credentials file not found at $CREDS" >&2
    echo "  (the tunnel exists but its credentials JSON is missing — try" >&2
    echo "  deleting it via 'cloudflared tunnel delete $NAME' and rerun.)" >&2
    exit 1
fi

# 3. Route DNS: <hostname> CNAME → <uuid>.cfargotunnel.com. Idempotent;
# cloudflared upserts the record.
echo "→ routing DNS: $HOSTNAME → $NAME"
cloudflared tunnel route dns "$NAME" "$HOSTNAME" || {
    echo "  (route dns failed — likely because the record already exists." >&2
    echo "  that's fine if it points at the same tunnel.)" >&2
}

# 4. Write a tunnel config the launcher will use.
cat > "$CFG" <<EOF
# Generated by bridge/setup-tunnel.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
tunnel: $EXISTING_UUID
credentials-file: $CREDS

ingress:
  - hostname: $HOSTNAME
    service: http://127.0.0.1:8787
  - service: http_status:404
EOF

cat <<EOF

=============================================================
  named tunnel ready
=============================================================
  name        : $NAME
  uuid        : $EXISTING_UUID
  hostname    : https://$HOSTNAME
  config file : $CFG

  Next: ./run-bridge.sh
  (it auto-detects bridge/cloudflared.yml and uses named-tunnel mode.)
=============================================================
EOF
